"use client";

import type { ProjectionResponse, Intervention, CitySummary } from "@/types";

export function generateReport(
  cityName: string,
  disasterType: string,
  summary: CitySummary | null,
  projection: ProjectionResponse | null,
  interventions: Intervention[],
  affectedZones: string
): string {
  const l = (s: string) => s + "\n";
  let r = "";
  r += l("=".repeat(55));
  r += l("DISS — Disaster Intervention Strategy Simulator");
  r += l("Cost of Inaction Report");
  r += l("=".repeat(55));
  r += l(`City: ${cityName}`);
  r += l(`Disaster type: ${disasterType}`);
  r += l(`Affected zones: ${affectedZones}`);
  if (summary) {
    r += l(`Total historic damage: $${summary.total_damage_bn.toFixed(0)}B`);
    r += l(`Historic events: ${summary.total_events}`);
    r += l(`Years covered: ${summary.years_covered}`);
  }
  r += l("");
  r += l("-".repeat(55));
  r += l("PROJECTED NEXT EVENT COST (if nothing changes)");
  r += l("-".repeat(55));
  if (projection) {
    const p = projection.projection;
    r += l(`  Direct damage: $${p.direct_damage_bn.toFixed(1)}B`);
    r += l(`  Displaced people: ${p.est_displaced.toLocaleString()}`);
    r += l(`  Displacement cost: $${p.displacement_cost_mn.toFixed(0)}M`);
    r += l(`  Healthcare cost: $${p.healthcare_cost_mn.toFixed(0)}M`);
    r += l(`  Lost wages: $${p.lost_wages_mn.toFixed(0)}M`);
    r += l(`  Homelessness risk: ${(p.est_displaced * 0.12).toFixed(0)}`);
    r += l(`  TOTAL: $${p.total_projected_cost_bn.toFixed(1)}B`);
  }
  r += l("");
  r += l("-".repeat(55));
  r += l("RECOMMENDED INTERVENTIONS");
  r += l("-".repeat(55));
  interventions.forEach((inv) => {
    r += l(`  #${inv.rank}: ${inv.action}`);
    r += l(`       Cost: $${inv.estimated_cost_mn}M  |  Saving: $${inv.projected_saving_mn}M  |  ROI: ${inv.roi}`);
  });
  r += l("");
  r += l("=".repeat(55));
  r += l("Generated by Disaster Intervention Strategy Simulator");
  r += l("USAII Global AI Hackathon 2026 | Graduate Track");
  r += l("Sources: FEMA OpenFEMA, CalFire, HCFCD, LA County");
  return r;
}
